//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSW.HealthCheck.Mvc5.Examples
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSWSqlDeployEntities : DbContext
    {
        public SSWSqlDeployEntities()
            : base("name=SSWSqlDeployEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SSWSqlVerifyMetaData> SSWSqlVerifyMetaDatas { get; set; }
    }
}
